parameters:
  - name: BuildPrereleaseVersion
    type: boolean
    default: true
  - name: PublishInternal
    type: boolean
    default: true
  - name: UseTypeSpecNext
    type: boolean
    default: false

trigger: none
pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - eng/packages/http-client-csharp

variables:
  - template: /eng/pipelines/templates/variables/image.yml

extends:
  template: /eng/common/pipelines/templates/stages/archetype-typespec-emitter.yml
  parameters:
    EmitterPackagePath: 
    BuildPrereleaseVersion: ${{ parameters.BuildPrereleaseVersion }}
    UseTypeSpecNext: ${{ parameters.UseTypeSpecNext }}
    PublishInternal: ${{ parameters.BuildPrereleaseVersion }}
    Packages:
      - name: http-client-csharp
        type: npm
    RegenerationJobCount: 5
    MinimumPerJob: 10
    OnlyGenerateTypespec: true
    PublishDependsOnTest: true
    TestMatrix: {}
 