parameters:
  - name: BuildPrereleaseVersion
    type: boolean
    default: true
  - name: PublishInternal
    type: boolean
    default: true
  - name: UseTypeSpecNext
    type: boolean
    default: false

trigger: none
pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - eng/packages/http-client-csharp

variables:
  - template: /eng/pipelines/templates/variables/image.yml

extends:
  template: /eng/common/pipelines/templates/stages/archetype-typespec-emitter.yml
  parameters:
    EmitterPackagePath: $(Build.SourcesDirectory)/eng/packages/http-client-csharp
    BuildPrereleaseVersion: ${{ parameters.BuildPrereleaseVersion }}
    UseTypeSpecNext: ${{ parameters.UseTypeSpecNext }}
    ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      ShouldPublish: true
      PublishInternal: ${{ parameters.PublishInternal }}
      PublishDependsOnTest: true
      
      ShouldRegenrate: true
      RegenerationJobCount: 5
      MinimumPerJob: 10
      OnlyGenerateTypespec: true
    Packages:
      - name: emitter
        file: azure-typespec-http-client-csharp-*.tgz
        type: npm
    TestMatrix:
        All:
          TestArguments: -UnitTests -GenerationChecks -Filter .
