// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "AZC0007:DO provide a minimal constructor that takes only the parameters required to connect to the service.", Justification = "False positives on minimal constructors", Scope = "namespaceanddescendants", Target = "~N:Azure.Developer.DevCenter")]
[assembly: SuppressMessage("Usage", "AZC0006:DO provide constructor overloads that allow specifying additional options.", Justification = "False positives on options constructors", Scope = "namespaceanddescendants", Target = "~N:Azure.Developer.DevCenter")]
[assembly: SuppressMessage("Usage", "AZC0031: Model name 'EnvironmentDefinition' ends with 'Definition'. Suggest to rename it to an appropriate name.", Justification = "Environment Definition is a Deployment Environment concept", Scope = "namespaceanddescendants", Target = "~N:Azure.Developer.DevCenter")]
[assembly: SuppressMessage("Usage", "AZC0030: Model name 'EnvironmentDefinitionParameter' ends with 'Parameter'. Suggest to rename it to 'EnvironmentDefinitionContent' or 'EnvironmentDefinitionPatch' or any other appropriate name.", Justification = "Environment Definition Parameter is a Deployment Environment concept", Scope = "namespaceanddescendants", Target = "~N:Azure.Developer.DevCenter")]
[assembly: SuppressMessage("Usage", "AZC0033: Model name 'DevBoxStartOperation' ends with 'Operation'. Suggest to rename it to 'DevBoxStartData' or 'DevBoxStartInfo', if an appropriate name could not be found.", Justification = "The name is aligned with the underlying API structure and cannot be changed.", Scope = "namespaceanddescendants", Target = "~N:Azure.Developer.DevCenter")]
[assembly: SuppressMessage("Usage", "AZC0033: Model name 'DevBoxRestartOperation' ends with 'Operation'. Suggest to rename it to 'DevBoxRestartData' or 'DevBoxRestartInfo', if an appropriate name could not be found.", Justification = "The name is aligned with the underlying API structure and cannot be changed.", Scope = "namespaceanddescendants", Target = "~N:Azure.Developer.DevCenter")]
[assembly: SuppressMessage("Usage", "AZC0033: Model name 'DevBoxRepairOperation' ends with 'Operation'. Suggest to rename it to 'DevBoxRepairData' or 'DevBoxRepairInfo', if an appropriate name could not be found.", Justification = "The name is aligned with the underlying API structure and cannot be changed.", Scope = "namespaceanddescendants", Target = "~N:Azure.Developer.DevCenter")]
